import streamlit as st
import sqlite3
import pandas as pd
from pathlib import Path

# Configure the page layout
st.set_page_config(page_title="AI SOC Triage", page_icon="🛡️", layout="wide")

# Path to the database you just created
BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "cases.db"

def load_cases():
    """Fetch the high-level list of cases for the sidebar."""
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql_query("SELECT case_id, timestamp, message_id, verdict FROM investigations ORDER BY timestamp DESC", conn)
        conn.close()
        return df
    except Exception as e:
        return pd.DataFrame()

def get_case_details(case_id):
    """Fetch the full Markdown summary and actions for a specific case."""
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("SELECT * FROM investigations WHERE case_id=?", (case_id,))
    case = c.fetchone()
    conn.close()
    return case

# Main UI
st.title("🛡️ AI Phishing Investigation Dashboard")
st.markdown("Review autonomous triage reports generated by the MCP Agent.")

df = load_cases()

if df.empty:
    st.info("No cases found in the database. Trigger the AI agent to investigate an alert!")
else:
    # Sidebar for case navigation
    st.sidebar.header("Recent Cases")
    
    # Create a clean display name for the dropdown
    df['display_name'] = df['case_id'] + " - " + df['message_id']
    selected_display = st.sidebar.selectbox("Select an Investigation", df['display_name'].tolist())
    
    # Extract the actual case ID from the selection
    selected_case_id = selected_display.split(" - ")[0]

    # Main case view
    if selected_case_id:
        details = get_case_details(selected_case_id)
        if details:
            case_id, timestamp, msg_id, verdict, summary, actions = details
            
            st.header(f"Case Report: {case_id}")
            st.caption(f"Alert ID: {msg_id} | Analyzed at: {timestamp}")
            
            # Color code the verdict
            if "COMPROMISE" in verdict.upper():
                st.error(f"**VERDICT:** {verdict}")
            elif "SUSPICIOUS" in verdict.upper() or "PHISHING" in verdict.upper():
                st.warning(f"**VERDICT:** {verdict}")
            else:
                st.success(f"**VERDICT:** {verdict}")
                
            st.divider()
            
            col1, col2 = st.columns([2, 1])
            
            with col1:
                st.subheader("Investigation Summary")
                st.markdown(summary)
                
            with col2:
                st.subheader("Recommended Response")
                st.info(actions)